"""empty message

Revision ID: 0efe1e0f0659
Revises: 00a548082864
Create Date: 2023-06-22 15:42:49.210061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efe1e0f0659'
down_revision = '00a548082864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_constraint('sighting_fk', type_='foreignkey')
        batch_op.drop_column('sighting_id')

    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('movie_fk', 'movie', ['movie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.drop_constraint('movie_fk', type_='foreignkey')
        batch_op.drop_column('movie_id')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sighting_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('sighting_fk', 'sighting', ['sighting_id'], ['id'])

    # ### end Alembic commands ###
