"""empty message

Revision ID: 12d3f2f0c7fa
Revises: 078e0e07d0af
Create Date: 2023-06-28 11:10:11.581655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d3f2f0c7fa'
down_revision = '078e0e07d0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.drop_column('approval')

    # ### end Alembic commands ###
