"""added coordinates for location

Revision ID: 1d3c2b777786
Revises: ffd8fba63b35
Create Date: 2023-07-07 16:39:03.442944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3c2b777786'
down_revision = 'ffd8fba63b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_long', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.drop_column('location_long')
        batch_op.drop_column('location_lat')

    # ### end Alembic commands ###
